# File paths
processed_data_path: "Recommender/data/processed"
model_path: "Recommender/models"

# MLflow Configuration
mlflow:
  experiment_name: "movielens_als_tuning"

# Optuna Configuration
optuna:
  n_trials: 5  # Reduced from 10

# CUDA Configuration
cuda:
  enabled: true  # Temporarily disabled while troubleshooting GPU setup
  device: 1      # GPU device index

# ALS Model Hyperparameters
als:
  factors: 50
  regularization: 0.01
  iterations: 20
  random_state: 42

# Data Preprocessing
preprocessing:
  min_user_interactions: 5
  min_movie_interactions: 5

# Splitting
splitting:
  test_size: 0.2
  stratify_by_user: True

# Evaluation
evaluation:
  k: 10

# Paths
paths:
  raw_data_dir: "Recommender/data/raw/"
  processed_data_dir: "Recommender/data/processed/"
  model_dir: "Recommender/models/"
  ratings_file: "ratings.csv"
  movies_file: "movies.csv"

# Model
model:
  name: "baseline_als_v1.pkl"

# Neural Network Configuration
neural:
  epochs: 10  # Conservative reduction from 30
  embedding_dim: 64
  layers: [128, 64, 32]
  dropout: 0.1
  learning_rate: 0.001
  batch_size: 3072  # Conservative increase from 2048 