name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Clear pip cache
      run: pip cache purge
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Recommender/requirements.txt
        pip install -r Recommender/requirements-dev.txt
    - name: Check ruff version
      run: ruff --version
    - name: Lint with ruff
      run: ruff check --output-format github .
    - name: Test with pytest
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Lowercase repository owner
      id: owner_string
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository_owner }}

    - name: Lowercase repository name
      id: repo_string
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.event.repository.name }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ steps.owner_string.outputs.lowercase }}/${{ steps.repo_string.outputs.lowercase }}:latest 